### ISSUE TITLE
Feature suggestion - colorized (per pod) output

### ISSUE THREAD

**Issue by nneul** [atombender/ktail#12]
I got here looking for an alternative to kubetail. One of it's limitations is that it doesn't see new pods as they are created. 

However, one feature of kubetail that is missing in ktail is it's colorization support. Kubetail picks a different randomly assigned color for each container - so if you are watching multiple, you can easily see from one set of output to the next.

That would be a nice feature to see added here.

**Comment by atombender** [comment]
Implemented in [1.2.0](https://github.com/atombender/ktail/releases/tag/v1.2.0).
