### ISSUE TITLE
WARNING: 50% of Log Entries are Duplicates

### ISSUE THREAD

**Issue by jmealo** [atombender/ktail#14]
@atombender: thanks for the tool

I've been chasing down log duplicates in our logging pipeline. Out of 562 million log entries, half of those are "unique". About 33% of them are repeated lines, where the previous line is byte-for-byte identical as the current line. I'm fairly certain that `ktail` is the culprit as the custom template I'm outputting is duplicated as well.

I used ``mmuniq-hash`` and ``mmuniq-bloom`` to get the 50% numbers. 

I'm not sure if k8s has made changes or if there is a bug.

Related to #4 -- however, no stateful sets were in use.

**Comment by atombender** [comment]
I have never seen this and don't know what might cause it. What version of Kubernetes are you on? It could be that upgrading to the newest client library version might help, if anything has changed in the API.

**Comment by jmealo** [comment]
@atombender: This was a client project on Azure AKS, K8s `v1.17.16`.

**Comment by ruckc** [comment]
I've seen this where new pods are spawning, ktail seems to sometimes identify the new pod multiple times, and therefore tails the pod's logs multiple times.

**Comment by jmealo** [comment]
To recap: It sounds like we need to add a check just before tailing a pod to make sure that we're not already tailing that pod. If this check exists, it appears to be faulty under some conditions. The check will need to take into account the error/failure state of a tail operation to prevent losing track of a given pod.

**Comment by ruckc** [comment]
@jmealo - it looks like the logic at issue is in the `controller.go:buildKey()`.  the `findContainerID()` doesn't return anything sometimes, so you end up with multiple tailers on a container, so i've created a #17 to address the issue.  Along with #16 for housekeeping.

**Comment by atombender** [comment]
Closed by #17.
