### ISSUE TITLE
--since-start does not work correctly with multiple containers

### ISSUE THREAD

**Issue by atombender** [atombender/ktail#18]

**Comment by ruckc** [comment]
are you referring to multiple containers in a single pod (i.e. init containers)?

**Comment by atombender** [comment]
Yes. If you have a pod `foo` with two containers `x` and `y`, then `--since-start` seems to arbitrarily pick a container to follow from the beginning.

**Comment by ruckc** [comment]
yeah, i've been experiencing this the past week or two it seems, i've been using -x to exclude the unnecessary containers.

**Comment by atombender** [comment]
Indeed. I'll try to look at it soon!

**Comment by atombender** [comment]
This should work now.
