### ISSUE TITLE
[FeatureRequest] make used color palette customizable

### ISSUE THREAD

**Issue by gerlazer** [atombender/ktail#22]
Since not everybody has good eyes or even have a specific colorblindness it would be cool to make the used palette customizable via configfile/parameter

**Comment by atombender** [comment]
That's a great idea. This is already supported; for example, you can use `--color-scheme solarized`. The full list of color schemes can be found [here](https://github.com/alecthomas/chroma/tree/master/styles).

Unfortunately there's no configuration file support yet, so for now, I would add an alias such as `alias ktail=/usr/local/bin/ktail --color-scheme <scheme>`.

**Comment by atombender** [comment]
I added support for using a configuration file. If you build from source (clone this repo and run `go install .`), you can try it out. See the readme for instructions.

**Comment by atombender** [comment]
This is now released in 1.4.0.
